

<value>::=  IDENTIFIER |
            NUMBER |
            STRING
            ;

<program>::=  <s_exp_list>
            ;

<s_exp>::=  <data> |
            SEPARATOR_LB <s_exp_list> SEPARATOR_RB
            ;


<s_exp_list>::= <s_exp> |
                <s_exp> <s_exp_list>
                ;

<data>::=   <value> <dtype>
            ;


<dtype>::=  <list> |
            <value> |
            <object>
            ;

<dtype_list>::= <dtype> |
                <dtype> <dtype_list>
                ;

<list>::=   KEYWORD_LIST SEPARATOR_LB <dtype_list> SEPARATOR_RB
            ;

<object>::= SEPARATOR_LB <s_exp_list> SEPARATOR_RB
            ;
