PROGRAM:        S_EXP_LIST
                ;

S_EXP_LIST:     S_EXP |
                S_EXP_LIST S_EXP
                ;

S_EXP:      DATA |
            SEPARATOR_LB S_EXP_LIST SEPARATOR_RB
            ;

KEY:        IDENTIFIER |
            STRING
            ;

DTYPE:      STRING |
            NUMBER
            ;


DATA:       CALC_EXP |
            KEYWORD_LIST SEPARATOR_LB DATA SEPARATOR_RB |
            KEY_VALUE_S_EXP
            ;


KEY_VALUE_S_EXP:        KEY DTYPE |
                        KEY SEPARATOR_LB DATA SEPARATOR_RB
                        ;

CALC_EXP:       KEYWORD_CALC SEPARATOR_LB OPERATOR_LIST SEPARATOR_RB
                ;

OPERAND:        IDENTIFIER |
                DTYPE
                ;

EXPRESSION:     SUMMA |
                EXPRESSION OPERATIONS_COMPARE SUMMA
                ;

SUMMA:      MULTIPLICATION |
            SUMMA OPERATIONS_SUM MULTIPLICATION
            ;

MULTIPLICATION:     OPERAND |
                    MULTIPLICATION OPERATIONS_MUL OPERAND
                    ;

OPERATOR_LIST:      OPERATOR |
                    OPERATOR OPERATOR_LIST
                    ;

OPERATOR_RETURN:        SEPARATOR_LB KEYWORD_RETURN OPERAND SEPARATOR_RB


OPERATOR:       OPERATOR_ASSIGNMENT |
                OPERATOR_DEFINE |
                OPERATOR_WHILE |
                OPERATOR_CALL |
                OPERATOR_PUSH
                ;

IDENTIFIER_LIST:        IDENTIFIER |
                        IDENTIFIER IDENTIFIER_LIST
                        ;

OPERATOR_PUSH:      SEPARATOR_LB KEYWORD_PUSH EXPRESSION SEPARATOR_RB
                    ;

OPERATOR_CALL:      SEPARATOR_LB IDENTIFIER SEPARATOR_LB IDENTIFIER_LIST SEPARATOR_RB SEPARATOR_RB
                    ;

OPERATOR_WHILE:     SEPARATOR_LB KEYWORD_WHILE SEPARATOR_LB OPERAND OPERATIONS_COMPARE OPERAND SEPARATOR_RB SEPARATOR_LB OPERATOR_LIST SEPARATOR_RB SEPARATOR_RB
                    ;

OPERATOR_ASSIGNMENT:        SEPARATOR_LB KEYWORD_VAR IDENTIFIER EXPRESSION SEPARATOR_RB |
                            SEPARATOR_LB KEYWORD_VAR IDENTIFIER OPERATOR_CALL SEPARATOR_RB
                            ;

OPERATOR_DEFINE:        SEPARATOR_LB KEYWORD_DEFINE IDENTIFIER SEPARATOR_LB IDENTIFIER_LIST SEPARATOR_RB SEPARATOR_LB OPERATOR_LIST OPERATOR_RETURN SEPARATOR_RB
                        ;

OPERATIONS_SUM:     SEPARATOR_PLUS |
                    SEPARATOR_MINUS
                    ;

OPERATIONS_COMPARE:     SEPARATOR_GT |
                        SEPARATOR_LT
                        ;

OPERATIONS_MUL:     SEPARATOR_MUL |
                    SEPARATOR_DIV
                    ;